"""Add audit_log with changed_by_info

Revision ID: 7ddf3869c5c5
Revises: 
Create Date: 2025-05-16 23:15:52.306711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddf3869c5c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('changed_by_info', sa.JSON(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###
