"""Request table

Revision ID: 7e151dde2623
Revises: 7ddf3869c5c5
Create Date: 2025-05-19 03:10:58.928589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e151dde2623'
down_revision = '7ddf3869c5c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('cer_month',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.SmallInteger(),
               existing_nullable=True)
        batch_op.alter_column('cer_day',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.SmallInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('cer_day',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True)
        batch_op.alter_column('cer_month',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True)

    # ### end Alembic commands ###
